### ISSUE TITLE
yes/no in vars turn into True/False in pdns.conf

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns-ansible#10]
If I write
```
pdns_backends:
  gsqlite3:
    dnssec: yes
    database: /var/lib/powerdns/pdns.sqlite3
```

I get `gsqlite3-dnssec=True` in my pdns.conf, which only works by accident. The `no` case is worse, as it still enables dnssec. Turning yes/no/true/false into bools is a documented Ansible feature.  `on` and `off` also appear to trigger the booleanization and I don't see where that happens.

As an admin, the workaround is to quote the variable `'yes'` (I'm also confused on why that helps). We could probably do something less surprising here.
