### ISSUE TITLE
40 branch

### ISSUE THREAD

**Issue by tiawaz** [PowerDNS/pdns-ansible#20]
When installing from the 40 branch on Centos7
```
  roles:
    - role: pdns-ansible
  vars:
    pdns_config:
      local-address: '{{ ansible_eth0.ipv4.address }}'
      allow-recursion: 'xxx.xxx.xxx.xxx'
      recursor: '{{ ansible_eth0.ipv4.address }}:5300'
    pdns_backends_mysql_credential:
      gmysql:
        priv_user: root
        priv_password: ***
        priv_host:
          - "%"
    pdns_backends:
      gmysql:
        host: 'localhost'
        port: 3306
        user: xxx
        password: ***
        dbname: pdns
    pdns_installation_type: 'packages'
    pdns_repo_provider: 'powerdns'
    pdns_repo_branch: '40'
```
i ran into the following problems:
1) The packages use etc/pdns as config dir, but the role defaults to /etc/powerdns
2)The packages put the schema into /usr/share/doc/pdns-backend-mysql-4.0.1/schema.mysql.sql, but the role defaults to /usr/share/doc/pdns-backend-mysql/schema.mysql.sql

**Comment by tiawaz** [comment]
both issues are easily worked around by fudging the vars in the role, simply adding 
```
- name: Load variables
  include_vars: '{{item}}'
  with_first_found:
    - files:
      - '{{ansible_os_family}}.yml'
      - 'default.yml'
      paths:
        - ../vars
```

to the main task and the adding my own vars/RedHat.yml
