### ISSUE TITLE
API via ansible?

### ISSUE THREAD

**Issue by huglester** [PowerDNS/pdns-ansible#31]
Hello

there is no support to enable API?

**Comment by atosatto** [comment]
Hi @huglester, you can enable the PowerDNS APIs (and/or the WebServer) setting in your groupvars

```yaml
pdns_config:
  # API Configuration
  api: yes
  api-key: "changeme"

  # Embedded webserver
  webserver: yes
  webserver-address: "0.0.0.0"
  webserver-port: "8081"
```

After applying this config to your PowerDNS setup you will be able to cURL the APIs with

```bash
curl -H 'X-API-Key: changeme' http://<pdns-ip>:8081/api/v1/servers/localhost/zones | jq .
```
