### ISSUE TITLE
systemd override not working for ExecStart

### ISSUE THREAD

**Issue by maximumG** [PowerDNS/pdns-ansible#77]
The pull request #53 added the possibility to override the default systemd unit file with some additionnal settings using `pdns_service_overrides` dict.

I was trying to override the default `ExecStart` statement in order to enable syslog support as it is explicitly disabled using the `--disable-syslog` option.

Unfortunaly, the way to override the ExecStart statement is first to have a NULL value and then override as in the following example.

```
[Service]
ExecStart=
Execstart=/usr/bin/pdns_server --disable-syslog ...
```
This won't work with the `pdns_service_overrides` dict as keys must be unique and needs to be registered twice. I guess it might be better (but less simple...) to have a list of dict such as this one.

```yaml
pdns_service_overrides:
  - key: ExecStart
    value: ""
  - key: ExecStart
    value: "/usr/bin/pdns_server --disable-syslog"
```
